### PR TITLE
Clarify that free ticket is one of the criteria

### PR DESCRIPTION
**Pull request by cczona**
I had taken for granted that speakers always are provided with free ticket to such conferences, so had treated that as an implicit criterion. Turns out that a handful require speakers to participate. For example, [requiring a speaker to pay $500 for full ticket or requiring a speaker to pay $200 for ticket to their speaking day](https://twitter.com/cczona/status/654365006209744896).

### CODE REVIEW

**Comment by webmaven** [comment]
Note that some conferences (such as PyCon), while generally requiring that speakers pay (indeed, that members of the volunteer staff pay as well), also offer financial assistance (including waiving the fee) for expenses such as travel and lodging when requested, as part of their efforts to increase the diversity of the conference membership: https://us.pycon.org/2015/assistance/

**Comment by cczona** [comment]
Indeed. PyCon provided [$200,000](https://sunlightfoundation.com/blog/2015/04/28/sunlight-labs-highlights-from-pycon-2015/) in financial aid last year. 

`"Conference may be eligible if it publicly advertises an option for any and all speakers to get the registration fee waived upon request."` was specified for that reason. Every PyCon speaker is eligible to request it. There is no category of speaker for whom there is no publicly advertised option of applying.

**Comment by webmaven** [comment]
Oops. I was mansplaining, wasn't I? :disappointed:

**Comment by cczona** [comment]
No prob. It's exciting to see someone's thinking at the criteria doc!

**Pull request merged**
